style: Formatting with shuck

diff --git a/wrap/gtrash b/wrap/gtrash
--- a/wrap/gtrash
+++ b/wrap/gtrash
@@ -1,12 +1,14 @@
 #!/bin/false
 # vim:set expandtab shiftwidth=4 filetype=zsh:
 # SPDX-License-Identifier: GPL-3.0-only
+
 #
 #
 # ~chewygumxx/zsh-config.git
 # ::: :/wrap/gtrash
 #
 #
+
 # Shadow zsh function for environment variable configuration of gtrash.
 # Intended for autoload from fpath directory.
 #
@@ -15,8 +17,8 @@
 #
 
 if [[ -z "$commands[gtrash]" ]]; then
-    echo "command 'gtrash' not found" >&2
-    return 127
+	echo "command 'gtrash' not found" >&2
+	return 127
 fi
 
 # Full path of home trash directory
@@ -42,7 +44,7 @@ local -x GTRASH_HOME_TRASH_FALLBACK_COPY="true"
 # Whether `gtrash put` should emulate `rm` and enforce recursive CLI options
 # including `-r`, `--recursive`, `-R`, and `-d`.
 # Can also be set with `--rm-mode`.
-# 
+#
 # Default: "false"
 local -x GTRASH_PUT_RM_MODE="false"
 
